version: "3.7"

services:
  web:
    container_name: "hello-world"
    image: rufatvalizadeh/helloworld:latest
    privileged: true
    ports:
      - "5949:80"
    volumes:
      - /var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock